Change instance name of the tinyManager class inside the Map class
With GCC we get :

In file included from Assets/Code/Lemming.h:3,
                 from Assets/Code/Actions.h:5,
                 from Assets/Code/Actions.cpp:1:
Assets/Code/Map.h:23:22: error: declaration of ‘tinyManager* Map::tinyManager’ changes meaning of ‘tinyManager’ [-fpermissive]
   23 |         tinyManager* tinyManager;
      |                      ^~~~~~~~~~~
In file included from Assets/Code/Map.h:3:
Assets/Code/tinyManager.h:12:7: note: ‘tinyManager’ declared here as ‘class tinyManager’
   12 | class tinyManager
      |       ^~~~~~~~~~~

So we need to compile with "-fpermissive" which is undesirable.

Change the instance name to tInstance to avoid this error.